permalink: /:year/:month/:day/:title 

title : Xavierskip
tagline: computer;internet;sport;music


name : xavier skip's blog
descripttion: WTF
url: http://xavierskip.com

production_url : http://xavierskip.com

markdown: rdiscount
pygments: true
paginate: 16
auto: true


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
  tracking_id : 'UA-35426524-1'
  getclicky :
  site_id : 